export function codeToKey(code) {
    switch (code) {
        case "Escape":
            return "Escape";
        case "IntlBackslash":
            return "§";
        case "Digit1":
            return "1";
        case "Digit2":
            return "2";
        case "Digit3":
            return "3";
        case "Digit4":
            return "4";
        case "Digit5":
            return "5";
        case "Digit6":
            return "6";
        case "Digit7":
            return "7";
        case "Digit8":
            return "8";
        case "Digit9":
            return "9";
        case "Digit0":
            return "0";
        case "Minus":
            return "-";
        case "Equal":
            return "=";
        case "Backspace":
            return "Backspace";
        case "Tab":
            return "Tab";
        case "KeyQ":
            return "q";
        case "KeyW":
            return "w";
        case "KeyE":
            return "e";
        case "KeyR":
            return "r";
        case "KeyT":
            return "t";
        case "KeyY":
            return "y";
        case "KeyU":
            return "u";
        case "KeyI":
            return "i";
        case "KeyO":
            return "o";
        case "KeyP":
            return "p";
        case "BracketLeft":
            return "[";
        case "BracketRight":
            return "]";
        case "Enter":
            return "Enter";
        case "CapsLock":
            return "CapsLock";
        case "KeyA":
            return "A";
        case "KeyS":
            return "S";
        case "KeyD":
            return "D";
        case "KeyF":
            return "F";
        case "KeyG":
            return "G";
        case "KeyH":
            return "H";
        case "KeyJ":
            return "J";
        case "KeyK":
            return "K";
        case "KeyL":
            return "L";
        case "Semicolon":
            return "";
            ";";
        case "Quote":
            return "'";
        case "Backslash":
            return "\\";
        case "ShiftLeft":
            return "Shift";
        case "Backquote":
            return "`";
        case "KeyZ":
            return "Z";
        case "KeyX":
            return "X";
        case "KeyC":
            return "C";
        case "KeyV":
            return "V";
        case "KeyB":
            return "B";
        case "KeyN":
            return "N";
        case "KeyM":
            return "M";
        case "Comma":
            return "", ";";
        case "Period":
            return ".";
        case "Slash":
            return "/";
        case "ShiftRight":
            return "Shift";
        case "ControlLeft":
            return "Control";
        case "AltLeft":
            return "Alt";
        case "MetaLeft":
            return "Meta";
        case "Space":
            return " ";
        case "MetaRight":
            return "Meta";
        case "AltRight":
            return "Alt";
        case "ArrowLeft":
            return "ArrowLeft";
        case "ArrowDown":
            return "ArrowDown";
        case "ArrowUp":
            return "ArrowUp";
        case "ArrowRight":
            return "ArrowRight";
        default:
            throw new Error(`Unkown code: ${code}`);
    }
}
